scrape_configs:
  - job_name: 'scrape-host'
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          host_gpu: monitoring-server
          hostname: monitoring-server
          node_type: cpu
          job: node-exporter

  - job_name: 'scrape-host-container'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          host_gpu: monitoring-server
          hostname: monitoring-server
          node_type: cpu
          job: cadvisor

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          hostname: monitoring-server
          host_gpu: monitoring-server
          node_type: cpu
          job: prometheus
